name: Raft

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: |
        IMAGE=raft-test:$(date +%s)
        docker build . --target=test -t $IMAGE
        docker run --rm $IMAGE
